# Generated by Django 3.2.8 on 2021-12-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='img_url',
            new_name='image',
        ),
    ]
